apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresw-pv
spec:
  storageClassName: manual
  hostPath:
    path: "/var/lib/postgresql/datad1"
  capacity:
    storage: 6Gi
  accessModes:
  - ReadWriteMany

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresw-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi